name = "tokenshit"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[env.production]
name = "tokenshit"

[assets]
directory = ".open-next/assets"
